version: '3'
services:
  vtiger:
    image: javanile/vtiger:7.1.0
    restart: unless-stopped
    environment:
      - VT_SITE_URL=http://127.0.0.1:8080
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 8080:80
    volumes:
      - ./:/app
      - vtiger:/var/lib/vtiger
    # networks:
    #   - megareso
  mysql:
    image: mysql:5.5
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql:rw
    # networks:
    #   - megareso
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    # networks:
    #   - megareso

volumes:
  mysql:
  vtiger:

networks:
  megareso:
    driver: bridge

